## 3x3 입력 : **filter size**

In [ ]:
import numpy as np

np.random.seed(1)

image = np.random.randint(5, size=(3,3))
print('image =\n', image)

filter = np.random.randint(5, size=(3,3))
print('filter =\n', filter)

image_x_filter = image * filter
print('image_x_filter =\n', image_x_filter)

convolution = np.sum(image_x_filter)
print('convolution =\n', convolution)

image =
 [[3 4 0]
 [1 3 0]
 [0 1 4]]
filter =
 [[4 1 2]
 [4 2 4]
 [3 4 2]]
image_x_filter =
 [[12  4  0]
 [ 4  6  0]
 [ 0  4  8]]
convolution =
 38


## 4x4 입력 : **stride**

In [ ]:
import numpy as np

np.random.seed(1)

image = np.random.randint(5, size=(4,4))
print('image =\n', image)

filter = np.random.randint(5, size=(3,3))
print('filter =\n', filter)

convolution = np.zeros((2,2))

for row in range(2):
	for col in range(2):
		window = image[row:row+3, col:col+3]
		print('window(%d, %d) =\n' %(row, col), window)
		print('window(%d, %d)*filter =\n' %(row, col), window*filter)
		convolution[row, col] = np.sum(window*filter)

print('convolution =\n', convolution)

image =
 [[3 4 0 1]
 [3 0 0 1]
 [4 4 1 2]
 [4 2 4 3]]
filter =
 [[4 2 4]
 [2 4 1]
 [1 0 1]]
window(0, 0) =
 [[3 4 0]
 [3 0 0]
 [4 4 1]]
window(0, 0)*filter =
 [[12  8  0]
 [ 6  0  0]
 [ 4  0  1]]
window(0, 1) =
 [[4 0 1]
 [0 0 1]
 [4 1 2]]
window(0, 1)*filter =
 [[16  0  4]
 [ 0  0  1]
 [ 4  0  2]]
window(1, 0) =
 [[3 0 0]
 [4 4 1]
 [4 2 4]]
window(1, 0)*filter =
 [[12  0  0]
 [ 8 16  1]
 [ 4  0  4]]
window(1, 1) =
 [[0 0 1]
 [4 1 2]
 [2 4 3]]
window(1, 1)*filter =
 [[0 0 4]
 [8 4 2]
 [2 0 3]]
convolution =
 [[31. 27.]
 [45. 23.]]


## 6x6 입력 : **padding**

In [ ]:
import numpy as np

np.random.seed(1)

image = np.random.randint(5, size=(4,4))
print('image =\n', image)

filter = np.random.randint(5, size=(3,3))
print('filter =\n', filter)

image_pad = np.pad(image,((1,1), (1,1)))
print('image_pad =\n', image_pad)

convolution = np.zeros((4,4))

for row in range(4):
	for col in range(4):
		window = image_pad[row:row+3, col:col+3]
		convolution[row, col] = np.sum(window*filter)

print('convolution =\n', convolution)

image =
 [[3 4 0 1]
 [3 0 0 1]
 [4 4 1 2]
 [4 2 4 3]]
filter =
 [[4 2 4]
 [2 4 1]
 [1 0 1]]
image_pad =
 [[0 0 0 0 0 0]
 [0 3 4 0 1 0]
 [0 3 0 0 1 0]
 [0 4 4 1 2 0]
 [0 4 2 4 3 0]
 [0 0 0 0 0 0]]
convolution =
 [[16. 25. 10.  4.]
 [38. 31. 27.  7.]
 [28. 45. 23. 16.]
 [42. 48. 49. 28.]]


## 4x4 합성 곱 : **pooling**

In [ ]:
import numpy as np

np.random.seed(1)

image = np.random.randint(5, size=(4,4))
print('image =\n', image)

filter = np.random.randint(5, size=(3,3))
print('filter =\n', filter)

image_pad = np.pad(image,((1,1), (1,1)))
print('image_pad =\n', image_pad)

convolution = np.zeros((4,4))

for row in range(4):
	for col in range(4):
		window = image_pad[row:row+3, col:col+3]
		convolution[row, col] = np.sum(window*filter)

print('convolution =\n', convolution)

max_pooled = np.zeros((2,2))

for row in range(0, 2):
	for col in range(0, 2):
		window = convolution[2*row:2*row+2, 2*col:2*col+2]
		max_pooled[row, col] = np.max(window)

print('max_pooled =\n', max_pooled)

image =
 [[3 4 0 1]
 [3 0 0 1]
 [4 4 1 2]
 [4 2 4 3]]
filter =
 [[4 2 4]
 [2 4 1]
 [1 0 1]]
image_pad =
 [[0 0 0 0 0 0]
 [0 3 4 0 1 0]
 [0 3 0 0 1 0]
 [0 4 4 1 2 0]
 [0 4 2 4 3 0]
 [0 0 0 0 0 0]]
convolution =
 [[16. 25. 10.  4.]
 [38. 31. 27.  7.]
 [28. 45. 23. 16.]
 [42. 48. 49. 28.]]
max_pooled =
 [[38. 27.]
 [48. 49.]]
