##1. 행 벡터, 열 벡터, 행렬

In [ ]:
#Numpy 라이브러리를 불러오고, np라는 별명으로 사용
import numpy as np

#행 벡터 생성
row = np.array([1,2,3])

#열 벡터 생성
col_1 = np.array([[1],
                [2],
                [3]])

col_2 = np.array([[1,2,3]])

#행렬 생성
matrix_1 = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

matrix_2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

#출력
print("행 벡터")
print(row)

print("\n열 벡터1")
print(col_1)

print("\n열 벡터2")
print(col_2)

print("\n행렬1")
print(matrix_1)

print("\n행렬2")
print(matrix_2)

행 벡터
[1 2 3]

열 벡터1
[[1]
 [2]
 [3]]

열 벡터2
[[1 2 3]]

행렬1
[[1 2 3]
 [4 5 6]
 [7 8 9]]

행렬2
[[1 2 3]
 [4 5 6]
 [7 8 9]]


##2. 배열 채우기

In [ ]:
number = np.arange(1,6)
print(number)

[1 2 3 4 5]


In [ ]:
number_zero = np.zeros((2,3))
print(number_zero)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
number_one = np.ones((2,3))
print(number_one)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
number_rand = np.random.rand(2,3)
print(number_rand)

[[0.82559081 0.2721674  0.84155651]
 [0.6884881  0.5021458  0.7814772 ]]


##3. 배열의 사칙연산

In [ ]:
a = np.array([[10,20,30],[40,50,60]])
b = np.array([[1,2,3],[4,5,6]])

print("행렬의 덧셈")
print(a+b)

print("\n행렬의 뺄셈")
print(a-b)

print("\n행렬의 곱셈")
print(a*b)

print("\n행렬의 나눗셈")
print(a/b)

행렬의 덧셈
[[11 22 33]
 [44 55 66]]

행렬의 뺄셈
[[ 9 18 27]
 [36 45 54]]

행렬의 곱셈
[[ 10  40  90]
 [160 250 360]]

행렬의 나눗셈
[[10. 10. 10.]
 [10. 10. 10.]]


##4. 행렬 함수

In [ ]:
a = np.array([[10,20,30],[40,50,60]])
b = np.array([[1,2,3],[4,5,6]])

print("행렬a")
print(a)

print("\n행렬b")
print(b)

#합(sum)
print("\n행렬의 a의 합")
print(np.sum(a))

print("\n행렬의 b의 합")
print(np.sum(b))

print("\n행렬 a,b에서 행의 원소 합계")
print(np.sum(a, axis=0))

print("\n행렬 a,b에서 열의 원소 합계")
print(np.sum(a, axis=1))

#평균(average)
print("\n행렬 a의 평균")
print(np.average(a))

print("\n행렬 a의 행별 원소 평균")
print(np.average(a, axis=0))

print("\n행렬 a의 열별 원소 평균")
print(np.average(a, axis=1))

행렬a
[[10 20 30]
 [40 50 60]]

행렬b
[[1 2 3]
 [4 5 6]]

행렬의 a의 합
210

행렬의 b의 합
21

행렬 a,b에서 행의 원소 합계
[50 70 90]

행렬 a,b에서 열의 원소 합계
[ 60 150]

행렬 a의 평균
35.0

행렬 a의 행별 원소 평균
[25. 35. 45.]

행렬 a의 열별 원소 평균
[20. 50.]


In [ ]:
#중앙값(median)
c = np.array([[100,200,300,400,500],
              [600,700,800,900,1000],
              [1,2,3,4,5],
              [6,7,8,9,0]])

print("행렬c")
print(c)

print("\n행렬 c의 중앙값")
print(np.median(c))

print("\n행렬 c의 행별 중앙값")
print(np.median(c, axis=0))

print("\n행렬 a의 열별 중앙값")
print(np.median(c, axis=1))

행렬c
[[ 100  200  300  400  500]
 [ 600  700  800  900 1000]
 [   1    2    3    4    5]
 [   6    7    8    9    0]]

행렬 c의 중앙값
54.5

행렬 c의 행별 중앙값
[ 53.  103.5 154.  204.5 252.5]

행렬 a의 열별 중앙값
[300. 800.   3.   7.]


In [ ]:
#최댓값(max), 최솟값(min)
c = np.array([[100,200,300,400,500],
              [600,700,800,900,1000],
              [1,2,3,4,5],
              [6,7,8,9,0]])

print("행렬c")
print(c)

print("\n행렬 c의 최댓값, 최솟값")
print(np.max(c), np.min(c))

print("\n행렬 c의 행별 최댓값")
print(np.max(c, axis=0))

print("\n행렬 a의 열별 최댓값")
print(np.max(c, axis=1))

print("\n행렬 c의 최댓값의 인덱스")
print(np.argmax(c))

print("\n행렬 c의 행별 최댓값 인덱스")
print(np.argmax(c, axis=0))

print("\n행렬 a의 열별 최댓값 인덱스")
print(np.argmax(c, axis=1))

행렬c
[[ 100  200  300  400  500]
 [ 600  700  800  900 1000]
 [   1    2    3    4    5]
 [   6    7    8    9    0]]

행렬 c의 최댓값, 최솟값
1000 0

행렬 c의 행별 최댓값
[ 600  700  800  900 1000]

행렬 a의 열별 최댓값
[ 500 1000    5    9]

행렬 c의 최댓값의 인덱스
9

행렬 c의 행별 최댓값
[1 1 1 1 1]

행렬 a의 열별 최댓값
[4 4 4 3]


In [ ]:
#분산(var)), 표준편차(std)
c = np.array([[100,200,300,400,500],
              [600,700,800,900,1000],
              [1,2,3,4,5],
              [6,7,8,9,0]])

print("행렬c")
print(c)

print("\n행렬 c의 분산, 표준편차")
print(np.var(c), np.std(c))

행렬c
[[ 100  200  300  400  500]
 [ 600  700  800  900 1000]
 [   1    2    3    4    5]
 [   6    7    8    9    0]]

행렬 c의 분산, 표준편차
115646.6875 340.06865115738026


In [ ]:
#any() : 특정 조건을 만족하는 원소가 1개라도 있는가
a = np.array([[10,20,30],[40,50,60]])
print(np.any(a>40))

#all() : 특정 조건을 모든 원소가 만족하는가?
print(np.all(a>40))

#where() : 특정 조건을 만족하는 것과 그렇지 않은 것의 다른 결과
print(np.where(a>40, a, 0))

True
False
[[ 0  0  0]
 [ 0 50 60]]
